version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
      - postgres
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - ENV POSTGRES_USER=postgres
      - ENV POSTGRES_PASSWORD=260702
      - ENV POSTGRES_DB=School
  ports:
    - 5432:5432
    
  